""" States and province codes
    https://developer.fedex.com/api/en-us/guides/api-reference.html#canadaprovincecodes
"""

st_pr_codes = {
    # Canada Province Codes
    'CA':{
        "Alberta": "AB",
        "British Columbia": "BC",
        "Manitoba": "MB",
        "New Brunswick": "NB",
        "Newfoundland": "NL",
        "Northwest Territories": "NT",
        "Nova Scotia": "NS",
        "Nunavut": "NU",
        "Ontario": "ON",
        "Prince Edward Island": "PE",
        "Quebec": "QC",
        "Saskatchewan": "SK",
        "Yukon": "YT"
    },
    # China Provinces and Regions
    "CN":{
        "Anhui": "Anhui",
        "Beijing": "Beijing",
        "Chongqing": "Chongqing",
        "Fujian": "Fujian",
        "Gansu": "Gansu",
        "Guangdong": "Guangdong",
        "Guizhou": "Guizhou",
        "Hainan": "Hainan",
        "Hebei": "Hebei",
        "Heilongjiang": "Heilongjiang",
        "Henan": "Henan",
        "Hubei": "Hubei",
        "Hunan": "Hunan",
        "Jiangsu": "Jiangsu",
        "Jiangxi": "Jiangxi",
        "Jilin": "Jilin",
        "Liaoning": "Liaoning",
        "Nei Mongol":"Nei  Mongol",
        "Qinghai": "Qinghai",
        "Shaanxi": "Shaanxi",
        "Shandong": "Shandong",
        "Shanghai": "Shanghai",
        "Shanxi": "Shanxi",
        "Sichuan": "Sichuan",
        "Tianjin": "Tianjin",
        "Xinjiang": "Xinjiang",
        "Yunnan": "Yunnan",
        "Zhejiang": "Zhejiang"
    },
    # India State Codes
    "IO":{
        "Andaman & Nicobar (U.T)": "AN",
        "Andhra Pradesh": "AP",
        "Arunachal Pradesh": "AR",
        "Assam": "AS",
        "Bihar": "BR",
        "Chattisgarh": "CG",
        "Chandigarh (U.T.)": "CH",
        "Daman & Diu (U.T.)": "DD",
        "Delhi (U.T.)": "DL",
        "Dadra and Nagar Haveli (U.T.)": "DN",
        "Goa": "GA",
        "Gujarat": "GJ",
        "Haryana": "HR",
        "Himachal Pradesh": "HP",
        "Jammu & Kashmir": "JK",
        "Jharkhand": "JH",
        "Karnataka": "KA",
        "Kerala": "KL",
        "Lakshadweep (U.T)": "LD",
        "Madhya Pradesh": "MP",
        "Maharashtra": "MH",
        "Manipur": "MN",
        "Meghalaya": "ML",
        "Mizoram": "MZ",
        "Nagaland": "NL",
        "Orissa": "OR",
        "Punjab": "PB",
        "Puducherry (U.T.)": "PY",
        "Rajasthan": "RJ",
        "Sikkim": "SK",
        "Tamil Nadu": "TN",
        "Tripura": "TR",
        "Uttaranchal": "UA",
        "Uttar Pradesh": "UP",
        "West Bengal": "WB"
    },
    # U.S. State Codes
    "US": {
        "Alabama": "AL",
        "Alaska": "AK",
        "Arizona": "AZ",
        "Arkansas": "AR",
        "California": "CA",
        "Colorado": "CO",
        "Connecticut": "CT",
        "Delaware": "DE",
        "District of Columbia": "DC",
        "Florida": "FL",
        "Georgia": "GA",
        "Hawaii": "HI",
        "Idaho": "ID",
        "Illinois": "IL",
        "Indiana": "IN",
        "Iowa": "IA",
        "Kansas": "KS",
        "Kentucky": "KY",
        "Louisiana": "LA",
        "Maine": "ME",
        "Maryland": "MD",
        "Massachusetts": "MA",
        "Michigan": "MI",
        "Minnesota": "MN",
        "Mississippi": "MS",
        "Missouri": "MO",
        "Montana": "MT",
        "Nebraska": "NE",
        "Nevada": "NV",
        "New Hampshire": "NH",
        "New Jersey": "NJ",
        "New Mexico": "NM",
        "New York": "NY",
        "North Carolina": "NC",
        "North Dakota": "ND",
        "Ohio": "OH",
        "Oklahoma": "OK",
        "Oregon": "OR",
        "Pennsylvania": "PA",
        "Rhode Island": "RI",
        "South Carolina": "SC",
        "South Dakota": "SD",
        "Tennessee": "TN",
        "Texas": "TX",
        "Utah": "UT",
        "Vermont": "VT",
        "Virginia": "VA",
        "Washington State": "WA",
        "West Virginia": "WV",
        "Wisconsin": "WI",
        "Wyoming": "WY",
        "Puerto Rico": "PR"
    },
    # United Arab Emirates (UAE) State Codes
    "AE": {
        "Abu Dhabi": "AB",
        "Ajman": "AJ",
        "Dubai": "DU",
        "Fujairah": "FU",
        "Ras al-Khaimah": "RA",
        "Sharjah": "SH",
        "Umm al-Quwain": "UM"
    }
}

